<div class="container breadcrumbs">
    <a href="<?= $this->url('home') ?>">Главная</a> <span class="separator">—</span>
    <a href="<?= $this->serverUrl('/nedvizhimost/city') ?>">Городская недвижимость</a><span class="separator">—</span>
    <span class="current">Вторичный рынок</span>
</div>
<section class="bg-blue no-bg-image bbg-gray">
    <div class="container">
        <h1 class="title fw">Вторичный рынок <span class="counter">(<?= $this->count;?>)</span></h1>
        <div class="filters">
<!--            <select>-->
<!--                <option>Москва</option>-->
<!--                <option>Санкт-Петербург</option>-->
<!--                <option>Новосибирск</option>-->
<!--                <option>Екатеринбург</option>-->
<!--                <option>Нижний Новгород</option>-->
<!--            </select>-->
            <div class="radio_group">
                <span class="label">Отсортировать:</span>
                <a href="<?= $this->serverUrl('/nedvizhimost/after-market/sort/new/1') ?>" class="option"><span class="option <?php echo ($this->active == 'new' ? 'active' : '') ?>">по новизне</span></a>
                <a href="<?= $this->serverUrl('/nedvizhimost/after-market/sort/price/1') ?>" class="option"><span class="option <?php echo ($this->active == 'price' ? 'active' : '') ?>">по цене</span></a>
<!--                <a href="--><?//= $this->serverUrl('/nedvizhimost/city/sort/date/1') ?><!--" class="option"><span class="option --><?php //echo ($this->active == 'date' ? 'active' : '') ?><!--">по дате ввода в эксплуатацию</span></a>-->
            </div>
            <div class="checkbox_group">
                <a href="<?= $this->serverUrl('/nedvizhimost/after-market/sort/profit/1') ?>" class="option"><span class="option starred <?php echo ($this->active == 'profit' ? 'active' : '') ?>">самые выгодные</span></a>

            </div>
<!--            <div class="right_pane">-->
<!--                <a class="icon cards" href="#"></a>-->
<!--                <a class="icon map" href="#"></a>-->
<!--            </div>-->
        </div>


        <?php
        if (count($this->special) == 0 && count($this->items) == 0) {
            echo "<div class='tile'><li><span class='item_link'>В данной категории не представлено недвижимости. <a href=" . $this->url('home') . ">Главная</a></span></li></div>";
        }
        ?>

        <ul class="tile">
            <?php
            /** @var \Application\Entity\RealtyObject $item */
            foreach ($this->special as $item) :?>

            <li class="tile_item highlighted">
                <a class="item_link" href="/nedvizhimost/apartment/<?= $item->getId(); ?>">
                    <?php if(count($item->getImages()) > 0) :?>
                        <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/<?= $item->getImages()[0]->getName();?>" alt="<?= $item->getName();?>"></div>
                    <?php  else :?>
                        <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="<?= $item->getName();?>"></div>
                    <?php endif;?>
                    <div class="adress"><?= $item->getName(); ?></div>
                    <div class="adress-map-marker"><?= $item->getLocation(); ?></div>
                    <div class="area"><strong><?= $item->getSquare();?></strong> м2</div>
                    <?php if(count($item->getCategory())) :?>
                        <div class="note"><?= $item->getCategory()[0]->getName();?></div>
                    <?php endif;?>
                    <hr />
                    <?php if (!empty($item->getPrice())) : ?>
                    <?php if (!empty($item->getSquare())) : ?>
                    <div class="cost"><?= number_format(round(str_replace(' ','',$item->getPrice())/$item->getSquare()), '0', '', ' ')?> руб./м<sup>2</sup></div>
                    <?php endif; ?>
                    <div class="flat_cost">Цена <strong><?= number_format($item->getPrice(), '0', '', ' ');?></strong> рублей</div>
                    <?php endif; ?>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>
            <?php endforeach;?>


            <?php
            /** @var \Application\Entity\RealtyObject $item */
            foreach ($this->items as $item) :?>

                <li class="tile_item">
                    <a class="item_link" href="/nedvizhimost/apartment/<?= $item->getId(); ?>">
                        <?php if(count($item->getImages()) > 0) :?>
                        <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/<?= $item->getImages()[0]->getName();?>" alt="<?= $item->getName();?>"></div>
                        <?php  else :?>
                        <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="<?= $item->getName();?>"></div>
                        <?php endif;?>
                        <div class="adress"><?= $item->getName(); ?></div>
                        <div class="adress-map-marker"><?= $item->getLocation(); ?></div>
                        <div class="area"><strong><?= $item->getSquare();?></strong> м2</div>
                        <?php if(count($item->getCategory())) :?>
                        <div class="note"><?= $item->getCategory()[0]->getName();?></div>
                        <?php endif;?>
                        <hr />
                        <?php if (!empty($item->getPrice())) : ?>
                            <?php if (!empty($item->getSquare())) : ?>
                                <div class="cost"><?= number_format(round(str_replace(' ','',$item->getPrice())/$item->getSquare()), '0', '', ' ')?> руб./м<sup>2</sup></div>
                            <?php endif; ?>
                            <div class="flat_cost">Цена <strong><?= number_format($item->getPrice(), '0', '', ' ');?></strong> рублей</div>
                        <?php endif; ?>
                        <div class="btn btn-yl hover-only">Подробнее</div>
                    </a>
                </li>

            <?php endforeach;?>

        </ul>
    </div>
    <div class="load_more_pane">
        <?php if ($this->page > 1) : ?>
        <a href="<?= $this->serverUrl($this->url) . ($this->page-1) ;?>" class="btn btn-yl">Предыдущие</a>
        <?php endif; if (!$this->lastPage) :?>
        <a href="<?= $this->serverUrl($this->url) . ($this->page+1) ;?>" class="btn btn-yl">Показать еще</a>
        <?php endif; ?>
    </div>
</section>
