<div class="container breadcrumbs">
    <a href="<?= $this->serverUrl('/nedvizhimost') ?>">Недвижимость</a> <span class="separator">—</span>
    <span class="current">Новостройки</span>
</div>
<section class="bg-blue no-bg-image bbg-gray">
    <div class="container">
        <h1 class="title fw">Новостройки <span class="counter">(23)</span></h1>
        <div class="filters">
            <select>
                <option>Москва</option>
                <option>Санкт-Петербург</option>
                <option>Новосибирск</option>
                <option>Екатеринбург</option>
                <option>Нижний Новгород</option>
            </select>
            <div class="radio_group">
                <span class="label">Отсортировать:</span>
                <span class="option active">по новизне</span>
                <span class="option">по цене</span>
                <span class="option">по дате ввода в эксплуатацию</span>
            </div>
            <div class="checkbox_group">
                <span class="option starred active">самые выгодные</span>
            </div>
            <div class="right_pane">
                <a class="icon cards" href="#"></a>
                <a class="icon map" href="#"></a>
            </div>
        </div>
        <ul class="tile">

            <li class="tile_item highlighted">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item highlighted">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item highlighted">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item highlighted">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item highlighted">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item highlighted">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item highlighted">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item highlighted">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

            <li class="tile_item">
                <a class="item_link" href="#">
                    <div class="img-wrapper"><img src="<?= $this->basePath();?>/img/img-1-2.png" alt="Реутов, ул. Комсомольская, д. 2"></div>
                    <div class="adress">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="adress-map-marker">Реутов,<br> ул. Комсомольская, д. 2</div>
                    <div class="area"><strong>52-136</strong> м2</div>
                    <div class="note">Однокомнатные, двухкомнатные, трехкомнатные</div>
                    <hr />
                    <div class="cost">70 000 руб./м<sup>2</sup></div>
                    <div class="flat_cost">Квартиры <strong>от 1 700 000 руб</strong></div>
                    <div class="btn btn-yl hover-only">Подробнее</div>
                </a>
            </li>

        </ul>
    </div>
    <div class="load_more_pane">
        <a href="#" class="btn btn-yl">Показать еще</a>
    </div>
</section>
