<h1>Сброс пароля</h1>
<?php
$form->prepare();
$this->headTitle('Сброс пароля');
if ($this->message != '') {
    echo <<<HTML
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
    <p>{$this->message}</p>
    <button name="buttons[close]">Закрыть</button>
</div>
</div>
HTML;
} else {
    echo $this->formBranchRender($form, 'bootstrap');
}
?>
<script>
    $(document).ready(function(){
        $(document).on('click', 'button[name="buttons[close]"]', function(){
            window.location.href = '/user';
        });
    });
</script>

